name: Destroy PR Environment

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  AWS_REGION: us-east-1
  DOMAIN_NAME: devrev-eng.ai
  ECR_REPOSITORY: mercor-django

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false
    
    - name: Terraform Init
      working-directory: ./infrastructure/terraform/environments/pr
      run: terraform init
    
    - name: Select Terraform Workspace
      working-directory: ./infrastructure/terraform/environments/pr
      run: |
        if terraform workspace select pr-${{ github.event.number }}; then
          echo "Workspace pr-${{ github.event.number }} found"
        else
          echo "Workspace pr-${{ github.event.number }} not found, nothing to destroy"
          exit 0
        fi
    
    - name: Terraform Destroy
      working-directory: ./infrastructure/terraform/environments/pr
      env:
        TF_VAR_pr_number: ${{ github.event.number }}
        TF_VAR_django_image: "dummy"  # Not needed for destroy
        TF_VAR_mongodb_image: mongo:7.0
        TF_VAR_domain_name: ${{ env.DOMAIN_NAME }}
      run: terraform destroy -auto-approve
    
    - name: Delete Terraform Workspace
      working-directory: ./infrastructure/terraform/environments/pr
      run: |
        terraform workspace select default
        terraform workspace delete pr-${{ github.event.number }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Delete ECR image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: pr-${{ github.event.number }}
      run: |
        # Delete the PR-specific image from ECR
        aws ecr batch-delete-image \
          --repository-name $ECR_REPOSITORY \
          --image-ids imageTag=$IMAGE_TAG || true
    
    - name: Comment PR on successful destruction
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.issue.number;
          const wasMerged = context.payload.pull_request.merged;
          const action = wasMerged ? 'merged' : 'closed';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🧹 **PR Environment Cleaned Up**
            
            The PR environment for #${prNumber} has been successfully destroyed after the PR was ${action}.
            
            **🗑️ Resources removed:**
            - ECS Cluster: \`cluster-pr-${prNumber}\`
            - VPC and networking components
            - Application Load Balancer
            - Route53 DNS record
            - EFS volume for MongoDB data
            - ECR Docker image
            - All associated security groups and IAM roles
            
            Thank you for using the PR deployment system! 🚀`
          });

  notify-failure:
    runs-on: ubuntu-latest
    needs: destroy
    if: failure()
    
    steps:
    - name: Comment PR on failure
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `⚠️ **Environment Cleanup Failed**
            
            The cleanup process for PR #${{ github.event.number }} encountered issues. Please check the [GitHub Actions logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
            
            **Manual cleanup may be required for:**
            - ECS services and tasks
            - Load balancers and target groups
            - VPC and networking resources
            - Route53 DNS records
            - ECR images
            
            Please contact the infrastructure team to ensure complete cleanup.`
          });
